# Generated by Django 3.2.12 on 2022-04-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_pages.category')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(max_length=700, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('structure', models.CharField(max_length=100, verbose_name='Состав')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('article', models.IntegerField(verbose_name='Артикль')),
                ('discount', models.IntegerField(verbose_name='Скидка(в процентах)')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие товара')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('sub_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_pages.subcategory', verbose_name='Подкатегория')),
            ],
        ),
    ]
