# Generated by Django 3.2.12 on 2022-04-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0005_images_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная?'),
        ),
    ]
