# Generated by Django 3.2.12 on 2022-04-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pages', '0006_alter_images_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='article',
        ),
        migrations.RemoveField(
            model_name='products',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Кол-во товара'),
        ),
    ]
